# Generated by Django 5.0.6 on 2024-06-13 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DumpTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_number', models.CharField(max_length=20, verbose_name='Бортовой номер самосвала')),
                ('model', models.CharField(max_length=20, verbose_name='Модель самосвала')),
                ('max_load', models.IntegerField(verbose_name='Максимальная грузоподъёмность, тонн')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название склада')),
                ('volume_before_unloading', models.IntegerField(verbose_name='Объём до разгрузки, тонн')),
                ('volume_after_unloading', models.IntegerField(verbose_name='Объём после разгрузки, тонн')),
                ('SiO2_procent', models.FloatField()),
                ('Fe_procent', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_load', models.IntegerField(verbose_name='Текущий вес груза, тонн')),
                ('SiO2_procent', models.FloatField(verbose_name='Содержание диоксида кремния, %')),
                ('Fe_procent', models.FloatField(verbose_name='Содержание железа, %')),
                ('coordinates', models.CharField(max_length=10, null=True, verbose_name='Координаты выгрузки')),
                ('current_truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quarryapp.dumptruck')),
            ],
        ),
    ]
